version: "3.8"
# Define the version of docker compose

services: # define services
  api: # define the backend service with name api
    build: ./api # specify relative path to the backend folder
    container_name: api_c # name of the container
    ports: # define port mapping
      - '4000:4000'
    volumes: #define volumes for backend and ignoring node_modules folder inside the container
      - ./api:/app
      - ./app/node_modules

      
  myblog: # define the frontend service with name myapp
    build: ./myblog
    container_name: myblog_c
    ports:
      - '3000:3000'
    volumes: #does not work on windows due to wsl, works on mac and linux
      - ./myblog:/app
      - ./app/node_modules
    stdin_open: true # these two commands start container in interactive mode
    tty: true
